import React from "react";
import { Container, Row, Col } from "react-bootstrap";

const ProductOverview = () => {
  return (
    <div className="bg-light text-dark py-5">
      <Container>
        <Row className="text-center mb-4">
          <Col>
            <h2 className="fw-bold">How the System Works</h2>
            <p className="lead">
              A modular and scalable engine that transforms input data into structured, context-aware outcomes.
            </p>
          </Col>
        </Row>

        <Row className="mb-5">
          <Col>
            <h4>Data Collector</h4>
            <p>
              This component gathers data from various inputs—internal systems, external APIs, or manual uploads. It ensures the data is cleaned, validated, and unified into a consistent format ready for processing.
            </p>

            <h4>Processing Module</h4>
            <p>
              Once the data is collected, the processing module applies analytical functions, extracts patterns, compares historical trends, and interprets structured information based on dynamic rules and definitions.
            </p>

            <h4>Result Generator</h4>
            <p>
              After evaluation, results are compiled into structured objects. These outcomes are designed to be readable, exportable, and integrable into existing systems or user dashboards.
            </p>

            <h4>Policy Checker</h4>
            <p>
              The output is matched against pre-configured business policies. This layer supports logic conditions, exception handling, and real-time checks to ensure compliance and contextual accuracy.
            </p>

            <h4>Update Monitor</h4>
            <p>
              Monitors connected data streams for changes over time. This agent triggers reprocessing as needed to ensure freshness and consistency of results across cycles.
            </p>
          </Col>
        </Row>

        <Row>
          <Col>
            <h4>Output Sample</h4>
            <p>
              A standard response object generated by the system could look like this:
            </p>
            <pre className="bg-dark text-white p-3 rounded">
{`{
  "id": "A1012",
  "status": "Processed",
  "score": 88,
  "tags": ["consistent behavior", "no issues found"],
  "summary": [
    "Active data streams verified",
    "No anomalies detected",
    "Aligned with internal thresholds"
  ]
}`}
            </pre>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default ProductOverview;